import { Deal, DealsFeedDto, FilterCriteria } from './dto/deals.ts';
import client from './client.ts';
import { plainToInstance } from 'class-transformer';
import { omitBy } from 'lodash';


export const dealsApi = {
    async getFeed(filter: FilterCriteria, offset: number, limit = 6): Promise<Deal[]> {
        const dto: DealsFeedDto = {
            filter: omitBy(filter, v => v === undefined || v === null),
            offset,
            limit,
        }
        const response = await client.post('/deals/feed', dto);

        if (!response.ok) {
            // Here we need some meaningful error handling...
            throw Error('Something went wrong');
        }

        const deals = response.data as Deal[];
        return deals.map(i => plainToInstance(Deal, i));
    },
};

export const sampleDeals: Deal[] = [
    {
        id: "1",
        title: "50% Off Premium Sushi Dinner for Two",
        description:
            "Enjoy an authentic Japanese sushi experience with this exclusive offer. Includes miso soup, edamame, choice of two specialty rolls, and green tea ice cream.",
        originalPrice: 89.99,
        discountPrice: 44.99,
        discountPercentage: 50,
        category: "Food & Drink",
        subcategory: "Japanese",
        tags: ["sushi", "dinner", "date night", "japanese cuisine"],
        location: {
            id: "1",
            lat: 37.7749,
            lng: -122.4194,
            address: "123 Sushi Way",
            city: "San Francisco",
            state: "CA",
            zipCode: "94103",
        },
        merchantName: "Sakura Sushi House",
        merchantRating: 4.7,
        quantitySold: 342,
        expiryDate: new Date("2025-07-15"),
        featuredDeal: true,
        imageUrl:
            "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "1",
                lat: 37.7749,
                lng: -122.4194,
                address: "123 Sushi Way",
                city: "San Francisco",
                state: "CA",
                zipCode: "94103",
            },
        ],
        finePrint:
            "Valid Monday-Thursday. Not valid on holidays. Reservation required.",
        reviewCount: 87,
        averageRating: 4.5,
        availableQuantity: 50,
    },
    {
        id: "2",
        title: "65% Off Full Body Massage",
        description:
            "Indulge in a relaxing 60-minute full body massage that will leave you feeling rejuvenated and stress-free.",
        originalPrice: 120,
        discountPrice: 42,
        discountPercentage: 65,
        category: "Beauty & Spas",
        subcategory: "Massage",
        tags: ["massage", "spa", "relaxation", "wellness"],
        location: {
            id: "2",
            lat: 37.7833,
            lng: -122.4167,
            address: "456 Relaxation Blvd",
            city: "San Francisco",
            state: "CA",
            zipCode: "94111",
        },
        merchantName: "Serenity Spa & Wellness",
        merchantRating: 4.9,
        quantitySold: 689,
        expiryDate: new Date("2025-06-30"),
        featuredDeal: true,
        imageUrl:
            "https://images.unsplash.com/photo-1600334129128-685c5582fd35?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "2",
                lat: 37.7833,
                lng: -122.4167,
                address: "456 Relaxation Blvd",
                city: "San Francisco",
                state: "CA",
                zipCode: "94111",
            },
        ],
        finePrint: "Appointments required. 24-hour cancellation notice required.",
        reviewCount: 156,
        averageRating: 4.8,
        availableQuantity: 75,
    },
    {
        id: "3",
        title: "40% Off Indoor Rock Climbing Experience",
        description:
            "Challenge yourself with a day pass to the city's premier indoor rock climbing facility. Includes gear rental and basic instruction.",
        originalPrice: 50,
        discountPrice: 30,
        discountPercentage: 40,
        category: "Activities & Events",
        subcategory: "Sports & Recreation",
        tags: ["rock climbing", "adventure", "fitness", "indoor"],
        location: {
            id: "3",
            lat: 37.7694,
            lng: -122.4862,
            address: "789 Climber's Edge",
            city: "San Francisco",
            state: "CA",
            zipCode: "94118",
        },
        merchantName: "Summit Indoor Climbing Center",
        merchantRating: 4.5,
        quantitySold: 210,
        expiryDate: new Date("2025-08-15"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1522163182402-834f871fd851?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "3",
                lat: 37.7694,
                lng: -122.4862,
                address: "789 Climber's Edge",
                city: "San Francisco",
                state: "CA",
                zipCode: "94118",
            },
        ],
        finePrint: "Valid for first-time customers only. Must sign waiver.",
        reviewCount: 64,
        averageRating: 4.6,
        availableQuantity: 100,
    },
    {
        id: "4",
        title: "75% Off Online Photography Masterclass",
        description:
            "Learn professional photography techniques from award-winning photographers in this comprehensive online course.",
        originalPrice: 199.99,
        discountPrice: 49.99,
        discountPercentage: 75,
        category: "Education",
        subcategory: "Online Courses",
        tags: ["photography", "online course", "education", "digital"],
        location: {
            id: "4",
            lat: 37.7749,
            lng: -122.4194,
            address: "Online",
            city: "San Francisco",
            state: "CA",
            zipCode: "94103",
        },
        merchantName: "Creative Vision Academy",
        merchantRating: 4.6,
        quantitySold: 845,
        expiryDate: new Date("2025-09-01"),
        featuredDeal: true,
        imageUrl:
            "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "4",
                lat: 37.7749,
                lng: -122.4194,
                address: "Online",
                city: "San Francisco",
                state: "CA",
                zipCode: "94103",
            },
        ],
        reviewCount: 231,
        averageRating: 4.7,
        availableQuantity: 999,
    },
    {
        id: "5",
        title: "30% Off Wine Tasting Tour for Two",
        description:
            "Sample premium wines from local vineyards with this guided tasting tour that includes transportation and light appetizers.",
        originalPrice: 150,
        discountPrice: 105,
        discountPercentage: 30,
        category: "Food & Drink",
        subcategory: "Wine Tasting",
        tags: ["wine", "tour", "date idea", "alcohol"],
        location: {
            id: "5",
            lat: 38.2919,
            lng: -122.458,
            address: "101 Vineyard Lane",
            city: "Napa",
            state: "CA",
            zipCode: "94559",
        },
        merchantName: "Valley Wine Tours",
        merchantRating: 4.8,
        quantitySold: 178,
        expiryDate: new Date("2025-07-31"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "5",
                lat: 38.2919,
                lng: -122.458,
                address: "101 Vineyard Lane",
                city: "Napa",
                state: "CA",
                zipCode: "94559",
            },
        ],
        finePrint:
            "Must be 21+ with valid ID. Reservation required 48 hours in advance.",
        reviewCount: 42,
        averageRating: 4.9,
        availableQuantity: 30,
    },
    {
        id: "6",
        title: "60% Off Teeth Whitening Treatment",
        description:
            "Get a brighter smile with this professional teeth whitening treatment that's gentle on sensitive teeth.",
        originalPrice: 250,
        discountPrice: 100,
        discountPercentage: 60,
        category: "Beauty & Spas",
        subcategory: "Dental",
        tags: ["teeth whitening", "dental", "cosmetic", "self-care"],
        location: {
            id: "6",
            lat: 37.7865,
            lng: -122.4001,
            address: "222 Bright Smile Drive",
            city: "San Francisco",
            state: "CA",
            zipCode: "94108",
        },
        merchantName: "Pearly Whites Dental Spa",
        merchantRating: 4.4,
        quantitySold: 156,
        expiryDate: new Date("2025-06-15"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "6",
                lat: 37.7865,
                lng: -122.4001,
                address: "222 Bright Smile Drive",
                city: "San Francisco",
                state: "CA",
                zipCode: "94108",
            },
        ],
        finePrint: "New patients only. Consultation required.",
        reviewCount: 38,
        averageRating: 4.3,
        availableQuantity: 25,
    },
    {
        id: "7",
        title: "25% Off Two-Hour Kayak Rental",
        description:
            "Explore the bay with this two-hour kayak rental, perfect for beginners and experienced paddlers alike.",
        originalPrice: 40,
        discountPrice: 30,
        discountPercentage: 25,
        category: "Activities & Events",
        subcategory: "Outdoor Activities",
        tags: ["kayak", "outdoors", "water sports", "bay area"],
        location: {
            id: "7",
            lat: 37.8065,
            lng: -122.4312,
            address: "333 Marina Blvd",
            city: "San Francisco",
            state: "CA",
            zipCode: "94123",
        },
        merchantName: "Bay Kayak Adventures",
        merchantRating: 4.3,
        quantitySold: 89,
        expiryDate: new Date("2025-08-31"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1544551763-92ab472cad5d?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "7",
                lat: 37.8065,
                lng: -122.4312,
                address: "333 Marina Blvd",
                city: "San Francisco",
                state: "CA",
                zipCode: "94123",
            },
        ],
        finePrint:
            "Subject to weather conditions. Reservation recommended on weekends.",
        reviewCount: 27,
        averageRating: 4.4,
        availableQuantity: 15,
    },
    {
        id: "8",
        title: "45% Off Three-Course Italian Dinner",
        description:
            "Enjoy authentic Italian cuisine with this three-course dinner including appetizer, main course, and dessert for two people.",
        originalPrice: 110,
        discountPrice: 60.5,
        discountPercentage: 45,
        category: "Food & Drink",
        subcategory: "Italian",
        tags: ["italian", "dinner", "pasta", "date night"],
        location: {
            id: "8",
            lat: 37.798,
            lng: -122.4071,
            address: "444 Pasta Lane",
            city: "San Francisco",
            state: "CA",
            zipCode: "94133",
        },
        merchantName: "Trattoria Milano",
        merchantRating: 4.6,
        quantitySold: 263,
        expiryDate: new Date("2025-07-10"),
        featuredDeal: true,
        imageUrl:
            "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "8",
                lat: 37.798,
                lng: -122.4071,
                address: "444 Pasta Lane",
                city: "San Francisco",
                state: "CA",
                zipCode: "94133",
            },
        ],
        finePrint: "Valid Sunday-Thursday. Tax and gratuity not included.",
        reviewCount: 71,
        averageRating: 4.7,
        availableQuantity: 35,
    },
    {
        id: "9",
        title: "70% Off One-Month Gym Membership",
        description:
            "Stay fit with full access to state-of-the-art equipment, classes, and facilities at this premium fitness center.",
        originalPrice: 85,
        discountPrice: 25.5,
        discountPercentage: 70,
        category: "Health & Fitness",
        subcategory: "Gyms",
        tags: ["gym", "fitness", "workout", "health"],
        location: {
            id: "9",
            lat: 37.7812,
            lng: -122.4134,
            address: "555 Fitness Ave",
            city: "San Francisco",
            state: "CA",
            zipCode: "94109",
        },
        merchantName: "Elite Fitness Club",
        merchantRating: 4.2,
        quantitySold: 412,
        expiryDate: new Date("2025-06-20"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "9",
                lat: 37.7812,
                lng: -122.4134,
                address: "555 Fitness Ave",
                city: "San Francisco",
                state: "CA",
                zipCode: "94109",
            },
            {
                id: "10",
                lat: 37.7857,
                lng: -122.4522,
                address: "777 Workout Blvd",
                city: "San Francisco",
                state: "CA",
                zipCode: "94118",
            },
        ],
        finePrint: "New members only. Photo ID required. No contract required.",
        reviewCount: 97,
        averageRating: 4.0,
        availableQuantity: 200,
    },
    {
        id: "10",
        title: "35% Off Luxury Hotel Stay",
        description:
            "Treat yourself to a one-night stay in a luxury hotel room with city views, including breakfast for two.",
        originalPrice: 350,
        discountPrice: 227.5,
        discountPercentage: 35,
        category: "Travel & Hotels",
        subcategory: "Hotels",
        tags: ["hotel", "luxury", "staycation", "weekend getaway"],
        location: {
            id: "11",
            lat: 37.7874,
            lng: -122.4075,
            address: "666 Grand Avenue",
            city: "San Francisco",
            state: "CA",
            zipCode: "94102",
        },
        merchantName: "Grand Plaza Hotel",
        merchantRating: 4.7,
        quantitySold: 134,
        expiryDate: new Date("2025-12-31"),
        featuredDeal: true,
        imageUrl:
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "11",
                lat: 37.7874,
                lng: -122.4075,
                address: "666 Grand Avenue",
                city: "San Francisco",
                state: "CA",
                zipCode: "94102",
            },
        ],
        finePrint:
            "Subject to availability. Blackout dates apply. Reservation required.",
        reviewCount: 53,
        averageRating: 4.6,
        availableQuantity: 20,
    },
    {
        id: "11",
        title: "50% Off Sunset Sailing Cruise",
        description:
            "Experience breathtaking views on this 2-hour sunset sailing cruise around the bay with complimentary champagne.",
        originalPrice: 90,
        discountPrice: 45,
        discountPercentage: 50,
        category: "Activities & Events",
        subcategory: "Tours",
        tags: ["sailing", "cruise", "sunset", "romantic"],
        location: {
            id: "12",
            lat: 37.8085,
            lng: -122.4096,
            address: "Pier 39",
            city: "San Francisco",
            state: "CA",
            zipCode: "94133",
        },
        merchantName: "Bay Sailing Adventures",
        merchantRating: 4.8,
        quantitySold: 286,
        expiryDate: new Date("2025-09-30"),
        featuredDeal: true,
        imageUrl:
            "https://images.unsplash.com/photo-1493894473891-10fc1e5dbd22?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "12",
                lat: 37.8085,
                lng: -122.4096,
                address: "Pier 39",
                city: "San Francisco",
                state: "CA",
                zipCode: "94133",
            },
        ],
        finePrint: "Weather permitting. Must be 21+ for complimentary champagne.",
        reviewCount: 79,
        averageRating: 4.9,
        availableQuantity: 12,
    },
    {
        id: "12",
        title: "80% Off Professional Headshot Session",
        description:
            "Update your professional image with a 30-minute headshot session including 3 retouched digital photos.",
        originalPrice: 250,
        discountPrice: 50,
        discountPercentage: 80,
        category: "Services",
        subcategory: "Photography",
        tags: ["headshots", "professional", "photography", "career"],
        location: {
            id: "13",
            lat: 37.7772,
            lng: -122.4382,
            address: "888 Camera Street",
            city: "San Francisco",
            state: "CA",
            zipCode: "94117",
        },
        merchantName: "Professional Image Studios",
        merchantRating: 4.5,
        quantitySold: 174,
        expiryDate: new Date("2025-07-01"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1552933529-e359b2477252?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "13",
                lat: 37.7772,
                lng: -122.4382,
                address: "888 Camera Street",
                city: "San Francisco",
                state: "CA",
                zipCode: "94117",
            },
        ],
        finePrint: "By appointment only. Additional photos available for purchase.",
        reviewCount: 41,
        averageRating: 4.7,
        availableQuantity: 25,
    },
    {
        id: "13",
        title: "20% Off Broadway Show Tickets",
        description:
            "Enjoy discounted tickets to this season's hottest Broadway show, with seating in premium orchestra sections.",
        originalPrice: 125,
        discountPrice: 100,
        discountPercentage: 20,
        category: "Activities & Events",
        subcategory: "Theater",
        tags: ["broadway", "theater", "entertainment", "show"],
        location: {
            id: "14",
            lat: 37.7785,
            lng: -122.4171,
            address: "999 Theater Way",
            city: "San Francisco",
            state: "CA",
            zipCode: "94102",
        },
        merchantName: "Golden Gate Theater",
        merchantRating: 4.6,
        quantitySold: 351,
        expiryDate: new Date("2025-06-15"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1503095396549-807759245b35?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "14",
                lat: 37.7785,
                lng: -122.4171,
                address: "999 Theater Way",
                city: "San Francisco",
                state: "CA",
                zipCode: "94102",
            },
        ],
        finePrint:
            "Subject to availability. Not valid for Saturday evening performances.",
        reviewCount: 86,
        averageRating: 4.8,
        availableQuantity: 40,
    },
    {
        id: "14",
        title: "55% Off Car Detailing Service",
        description:
            "Comprehensive car detailing package including exterior wash, wax, interior cleaning, and tire shine.",
        originalPrice: 180,
        discountPrice: 81,
        discountPercentage: 55,
        category: "Automotive",
        subcategory: "Car Services",
        tags: ["car detailing", "automotive", "cleaning", "maintenance"],
        location: {
            id: "15",
            lat: 37.7581,
            lng: -122.4245,
            address: "1010 Auto Plaza",
            city: "San Francisco",
            state: "CA",
            zipCode: "94110",
        },
        merchantName: "Pristine Auto Detail",
        merchantRating: 4.4,
        quantitySold: 92,
        expiryDate: new Date("2025-08-15"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "15",
                lat: 37.7581,
                lng: -122.4245,
                address: "1010 Auto Plaza",
                city: "San Francisco",
                state: "CA",
                zipCode: "94110",
            },
        ],
        finePrint:
            "SUVs and oversized vehicles subject to additional fee. Appointment required.",
        reviewCount: 25,
        averageRating: 4.2,
        availableQuantity: 30,
    },
    {
        id: "15",
        title: "42% Off Cooking Class for Two",
        description:
            "Learn to prepare a gourmet three-course meal with hands-on instruction from a professional chef.",
        originalPrice: 190,
        discountPrice: 110,
        discountPercentage: 42,
        category: "Food & Drink",
        subcategory: "Cooking Classes",
        tags: ["cooking class", "chef", "gourmet", "date night"],
        location: {
            id: "16",
            lat: 37.7752,
            lng: -122.4232,
            address: "1111 Culinary Blvd",
            city: "San Francisco",
            state: "CA",
            zipCode: "94103",
        },
        merchantName: "Gourmet Cooking Academy",
        merchantRating: 4.7,
        quantitySold: 127,
        expiryDate: new Date("2025-07-15"),
        featuredDeal: false,
        imageUrl:
            "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=800&auto=format&fit=crop",
        redemptionLocations: [
            {
                id: "16",
                lat: 37.7752,
                lng: -122.4232,
                address: "1111 Culinary Blvd",
                city: "San Francisco",
                state: "CA",
                zipCode: "94103",
            },
        ],
        finePrint:
            "All ingredients included. No experience necessary. Must be 18+.",
        reviewCount: 32,
        averageRating: 4.8,
        availableQuantity: 8,
    },
];
